// tests/simple-sections.spec.ts
// ─────────────────────────────────────────────────────────────
// ELEVEN home-page sections, one shared battery of checks.
//
//   BL    brand_logo             GB    grid_banner
//   MQ    marquee                NL    newsletter
//   NC    number_counter         SPEC  specification_section
//   IWT   icon_with_text         GS    grid_showcase
//   IB    image_banner           SG    spotlight_gallery
//                                IG    image_gallery
//
// These sections present content without interactive state: nothing
// to drive, no multi-step flow, no drag handle. What they DO have in
// common is everything that quietly rots — a missing alt attribute, a
// link left pointing at "#", an item that collapses to no height,
// text that spills its box, contrast that drifts below readable.
//
// So they are written once, parameterised by prefix, rather than as
// eleven near-identical spec files. Adding a twelfth such section is
// a row in utils/simple-sections.js plus a manifest entry — no new
// spec, no new page object.
//
// Every expectation comes from data/presets.json, generated by
// `npm run sync:simple` against the live stores. A preset that does
// not ship a section never collects its checks (playwright.config.ts).
// ─────────────────────────────────────────────────────────────

import { test, expect } from '../utils/fixtures';
import AxeBuilder from '@axe-core/playwright';
import { SimpleSectionPage } from '../pages/SimpleSectionPage.js';
import { SIMPLE_SECTIONS, rootSelector } from '../utils/simple-sections.js';
import { mountNarrator, spot, spotVerdicts } from '../utils/demo-hud.js';
import { checksFor } from '../utils/slideshow-checks.js';

for (const section of SIMPLE_SECTIONS) {
  const { type, prefix, label, item } = section;

  const { assertRenderHealth, expectNoMissingTranslations, assertNoDeadOrUnsafeLinks,
          assertNoPageOverflow, assertContentInsideBox,
          expectNoPlaceholderText } = checksFor(prefix);

  test.describe(label, () => {
    let sp: SimpleSectionPage;

    // A preset that does not ship this section never reaches here —
    // the config drops the whole prefix. This is the safety net for
    // when the manifest and the store disagree.
    test.skip(({ preset }) => !(preset.sections?.[type] > 0),
      `This preset does not ship a ${label} section.`);

    test.beforeEach(async ({ page, preset }, testInfo) => {
      sp = new SimpleSectionPage(page, preset, section);
      await mountNarrator(page, {
        title: testInfo.title,
        preset: preset.key,
        spotlight: rootSelector(type),
      });
      await sp.open();
    });

    /** Walk every instance of this section the preset declares. */
    const eachInstance = async (preset: any, fn: (i: number, expected: any) => Promise<void>) => {
      const declared = preset.simpleSections?.[type] ?? [];
      for (let i = 0; i < declared.length; i++) {
        await sp.focus(i);
        await fn(i, declared[i]);
      }
    };

    // =========================================================
    // Render & structure
    // =========================================================
    test(`${prefix}-RENDER-01 — the section is present and visible`, async ({ preset }) => {
      await spot(sp.roots());
      expect(
        await sp.instanceCount(),
        `${prefix}-RENDER-01 / count: the manifest declares ` +
          `${preset.sections[type]} ${label} section(s) for ${preset.label}. ` +
          `A different number means one was added, removed, or failed to render.`
      ).toBe(preset.sections[type]);

      await expect(sp.root()).toBeVisible();
    });

    test(`${prefix}-RENDER-02 — it holds the expected number of items`, async ({ preset }) => {
      test.skip(!item, `${label} has no repeating item to count.`);
      await eachInstance(preset, async (i, expected) => {
        await spot(sp.items(i));
        expect(
          await sp.itemCount(i),
          `${prefix}-RENDER-02 / item-count: instance ${i + 1} should hold ` +
            `${expected.items} item(s) but holds ${await sp.itemCount(i)}. ` +
            `If the content genuinely changed, re-run "npm run sync:simple".`
        ).toBe(expected.items);
      });
    });

    test(`${prefix}-RENDER-03 — nothing has collapsed`, async ({ preset }) => {
      await eachInstance(preset, async (i) => {
        const target = item ? sp.items(i) : sp.root(i);
        await assertRenderHealth(target, { minHeight: 20 });
      });
    });

    test(`${prefix}-RENDER-04 — no missing translation keys`, async ({ preset }) => {
      await eachInstance(preset, async (i) => {
        await spot(sp.root(i));
        await expectNoMissingTranslations(sp.root(i));
      });
    });

    test(`${prefix}-RENDER-05 — no raw Liquid reached the browser`, async ({ preset }) => {
      await eachInstance(preset, async (i) => {
        await spot(sp.root(i));
        const leaks = await sp.liquidLeaks(i);
        expect(
          leaks,
          `${prefix}-RENDER-05 / liquid-leak: un-rendered Liquid is present in instance ` +
            `${i + 1}:\n  ${leaks.join('\n  ')}\n` +
            `A "{{ ... }}" that reaches the browser means the theme printed the template ` +
            `source instead of evaluating it.`
        ).toEqual([]);
      });
    });

    test(`${prefix}-CONTENT-01 — no theme placeholder text is left on the page`, async ({ preset }) => {
      await eachInstance(preset, async (i) => {
        await expectNoPlaceholderText(sp.root(i));
      });
    });

    // =========================================================
    // Media
    // =========================================================
    test(`${prefix}-MEDIA-01 — every image has alt text`, async ({ preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.images, `Instance ${i + 1} of ${label} has no images.`);
        const alts = await sp.imageAlts(i);
        const verdicts = alts.map((a) => (a.alt ?? '').trim().length > 0);
        await spotVerdicts(sp.images(i), verdicts);

        const missing = alts
          .map((a, n) => (verdicts[n] ? null : `#${n + 1} (${a.src})`))
          .filter(Boolean);
        expect(
          missing,
          `${prefix}-MEDIA-01 / missing-alt: image(s) ${missing.join(', ')} in instance ` +
            `${i + 1} have no alt text. If the image fails to load nothing takes its ` +
            `place, and a screen reader announces only "image".`
        ).toEqual([]);
      });
    });

    test(`${prefix}-MEDIA-02 — every image actually loaded`, async ({ preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.images, `Instance ${i + 1} of ${label} has no images.`);
        await spot(sp.images(i));
        const broken = await sp.brokenImages(i);
        expect(
          broken,
          `${prefix}-MEDIA-02 / broken-image: image(s) ${broken.join(', ')} in instance ` +
            `${i + 1} finished loading with no dimensions — the browser is showing a ` +
            `broken-image icon.`
        ).toEqual([]);
      });
    });

    test(`${prefix}-MEDIA-03 — the expected number of images is present`, async ({ preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.images, `Instance ${i + 1} of ${label} has no images.`);
        expect(
          await sp.imageCount(i),
          `${prefix}-MEDIA-03 / image-count: instance ${i + 1} should show ` +
            `${expected.images} image(s).`
        ).toBe(expected.images);
      });
    });

    // =========================================================
    // Links
    // =========================================================
    test(`${prefix}-LINK-01/03/04 — no dead, unsafe or unlabelled links`, async ({ preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.links, `Instance ${i + 1} of ${label} has no links.`);
        await spot(sp.links(i));
        await assertNoDeadOrUnsafeLinks(sp.root(i));
      });
    });

    test(`${prefix}-LINK-02 — links point somewhere real`, async ({ preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.links, `Instance ${i + 1} of ${label} has no links.`);
        const links = await sp.linkHrefs(i);
        const isPlaceholder = (h: string | null) => !h || h === '#' || h.trim() === '';
        const verdicts = links.map((l) => !isPlaceholder(l.href));
        await spotVerdicts(sp.links(i), verdicts);

        const dead = links
          .filter((l) => isPlaceholder(l.href))
          .map((l) => `"${l.text || '(no text)'}"`);
        expect(
          dead,
          `${prefix}-LINK-02 / placeholder: ${dead.length} of ${links.length} link(s) in ` +
            `instance ${i + 1} have href="#" and navigate nowhere: ${dead.join(', ')}.\n` +
            `They look and behave like real links to a shopper — the pointer changes, they ` +
            `are clickable — but nothing happens.`
        ).toEqual([]);
      });
    });

    test(`${prefix}-LINK-05 — every link still resolves`, async ({ page, preset }) => {
      await eachInstance(preset, async (i, expected) => {
        test.skip(!expected.links, `Instance ${i + 1} of ${label} has no links.`);
        const links = await sp.linkHrefs(i);
        const broken: string[] = [];

        // De-duplicate: galleries repeat the same destination many times.
        const seen = new Set<string>();
        for (const { text, href } of links) {
          if (!href || href.startsWith('#') || href.startsWith('mailto:') ||
              href.startsWith('tel:') || href.startsWith('javascript:')) continue;
          const url = new URL(href, page.url()).toString();
          if (seen.has(url)) continue;
          seen.add(url);

          const res = await page.request.get(url, { failOnStatusCode: false }).catch(() => null);
          const status = res?.status() ?? 0;
          if (status >= 400 || status === 0) {
            broken.push(`"${text}" -> ${url} (${status || 'unreachable'})`);
          }
        }

        expect(
          broken,
          `${prefix}-LINK-05 / dead-link: link(s) in instance ${i + 1} point at pages that ` +
            `no longer exist:\n  ${broken.join('\n  ')}`
        ).toEqual([]);
      });
    });

    // =========================================================
    // Layout
    // =========================================================
    test(`${prefix}-LAYOUT-01 — no horizontal page overflow`, async ({ page }) => {
      await assertNoPageOverflow(page);
    });

    test(`${prefix}-LAYOUT-02 — content stays inside the section`, async ({ preset }) => {
      test.skip(!item, `${label} has no repeating item to measure.`);
      await eachInstance(preset, async (i) => {
        // Several of these sections are Swiper-backed (brand logos,
        // icon rows, galleries, counters), so the off-stage slides sit
        // well outside the visible frame on purpose. Measure only what
        // is actually on screen.
        await assertContentInsideBox(sp.root(i), sp.items(i), { onlyInView: true });
      });
    });

    test(`${prefix}-LAYOUT-03 — it holds across the viewport matrix`, async ({ page, preset }) => {
      for (const width of [1440, 1200, 1024, 768, 390]) {
        await page.setViewportSize({ width, height: 900 });
        await sp.focus(0);
        await expect(
          sp.root(),
          `${prefix}-LAYOUT-03 / breakpoint: the ${label} section stopped being visible ` +
            `at ${width}px.`
        ).toBeVisible();
        await assertNoPageOverflow(page);
      }
    });

    // =========================================================
    // Accessibility
    // =========================================================
    test(`${prefix}-A11Y-01 — no critical accessibility violations`, async ({ page, preset }) => {
      await eachInstance(preset, async (i) => {
        await spot(sp.root(i));
        const id = await sp.root(i).getAttribute('id');
        const results = await new AxeBuilder({ page })
          .include(`#${id}`)
          .withTags(['wcag2a', 'wcag2aa'])
          .analyze();

        const critical = results.violations.filter(
          (v) => v.impact === 'critical' || v.impact === 'serious'
        );
        expect(
          critical.map((v) => `${v.id}: ${v.help} -> ${v.nodes[0]?.target?.join(' ')}`),
          `${prefix}-A11Y-01 / axe: ${critical.length} critical violation(s) in instance ${i + 1}.`
        ).toEqual([]);
      });
    });

    test(`${prefix}-A11Y-02 — text contrast is at least 4.5:1`, async ({ page, preset }) => {
      await eachInstance(preset, async (i) => {
        const id = await sp.root(i).getAttribute('id');
        const results = await new AxeBuilder({ page })
          .include(`#${id}`)
          .withRules(['color-contrast'])
          .analyze();

        expect(
          results.violations.flatMap((v) => v.nodes.map((n) => n.target.join(' '))),
          `${prefix}-A11Y-02 / contrast: text in instance ${i + 1} fails the 4.5:1 minimum.`
        ).toEqual([]);
      });
    });
  });
}
