// pages/SlideshowPage.js
// ─────────────────────────────────────────────────────────────
// Page Object for the home-page slideshow section.
//
// This is the pattern for every section type: ONE page object per
// section TYPE, not per preset store. A slideshow behaves the same
// wherever it appears because it is the same theme code — what varies
// per preset is whether the section exists, how many there are, and
// which controls (dots / arrows) are switched on.
//
// Those variations come from the preset manifest in data/presets.json
// (generated by `npm run sync:sections`), so this class stays free of
// any store-specific knowledge.
// ─────────────────────────────────────────────────────────────

import { BasePage } from './BasePage.js';

export class SlideshowPage extends BasePage {

  constructor(page, preset = null) {
    super(page, preset);
    this.s = this.locators.slideshow;
  }

  // ── Section getters ─────────────────────────────────────────

  // Every slideshow section on the page (a preset may configure more
  // than one, which is why this is not scoped to `.first()`).
  sections()          { return this.page.locator(this.s.section); }
  section(index = 0)  { return this.sections().nth(index); }

  // ── Slide getters, scoped to one slideshow ──────────────────

  slides(index = 0)      { return this.section(index).locator(this.s.slide); }
  slideAt(n, index = 0)  { return this.slides(index).nth(n); }
  activeSlide(index = 0) { return this.section(index).locator(this.s.activeSlide).first(); }
  images(index = 0)      { return this.section(index).locator(this.s.image); }
  textBlocks(index = 0)  { return this.section(index).locator(this.s.text); }
  // Text of the ACTIVE slide only. Layout assertions must use this —
  // off-screen slides sit outside the visible box by design, so
  // measuring them against the active slide reports false overflow.
  activeTextBlocks(index = 0) { return this.activeSlide(index).locator(this.s.text); }
  ctas(index = 0)        { return this.section(index).locator(this.s.cta); }
  bullets(index = 0)     { return this.section(index).locator(this.s.bullets); }
  bulletAt(n, index = 0) { return this.bullets(index).nth(n); }
  nextArrow(index = 0)   { return this.section(index).locator(this.s.nextArrow).first(); }
  prevArrow(index = 0)   { return this.section(index).locator(this.s.prevArrow).first(); }

  // ── Actions ─────────────────────────────────────────────────

  // Open the home page and wait for the first slideshow to render.
  //
  // Deliberately no scrollIntoViewIfNeeded(): that call waits for a
  // stable bounding box, which an autoplaying carousel never settles
  // into, so it times out even though the section is visible from the
  // first paint. Playwright auto-scrolls before any real interaction.
  async open() {
    await this.gotoHome();
    await this.section().waitFor({ state: 'visible', timeout: 30_000 });

    // Wait for Swiper to finish initialising before any test reads
    // slide counts or clicks an arrow. Without this, a run under heavy
    // parallel load can measure a half-built carousel (0 slides) or
    // click an arrow whose handler is not bound yet — which shows up as
    // an intermittent failure that never reproduces in isolation.
    await this.section()
      .locator(`${this.s.swiper}.swiper-initialized`)
      .first()
      .waitFor({ state: 'attached', timeout: 15_000 })
      .catch(() => {
        /* Presets without the initialised class still run the DOM checks. */
      });
  }

  // ── Queries ─────────────────────────────────────────────────

  // How many slideshow sections the page actually renders.
  async sectionCount() {
    return this.sections().count();
  }

  // How many authored slides the given slideshow carries.
  async slideCount(index = 0) {
    return this.slides(index).count();
  }

  // Which slide is currently active, as a 0-based index. Returns -1
  // when no slide carries the active class.
  async activeSlideIndex(index = 0) {
    return this.section(index).evaluate((sec, sel) => {
      const slides = [...sec.querySelectorAll(sel.slide)];
      return slides.findIndex((s) => s.classList.contains('swiper-slide-active'));
    }, this.s);
  }

  // True when this slideshow exposes clickable pagination bullets.
  async hasBullets(index = 0) {
    return (await this.bullets(index).count()) > 0;
  }

  // True when this slideshow exposes a next / previous arrow.
  async hasNextArrow(index = 0) {
    return (await this.nextArrow(index).count()) > 0;
  }

  async hasPrevArrow(index = 0) {
    return (await this.prevArrow(index).count()) > 0;
  }

  // Wait until the carousel is no longer on slide `before`.
  //
  // Watches Swiper's realIndex, NOT the DOM's .swiper-slide-active
  // position: with loop enabled Swiper rotates slides through the DOM
  // and keeps the active one at a fixed position, so the DOM index can
  // stay identical while the carousel genuinely moves.
  async waitForActiveChange(index, before) {
    await this.page.waitForFunction(
      ({ sectionSel, swiperSel, idx, prev }) => {
        const section = document.querySelectorAll(sectionSel)[idx];
        const swiper = section?.querySelector(swiperSel)?.swiper;
        if (!swiper) return false;
        return swiper.realIndex !== prev;
      },
      { sectionSel: this.s.section, swiperSel: this.s.swiper, idx: index, prev: before },
      { timeout: 10_000 }
    );
    return this.realIndex(index);
  }

  // Block until Swiper is not mid-transition.
  //
  // Swiper IGNORES a navigation click while it is still animating, so a
  // click fired during a transition is silently swallowed and the wait
  // that follows times out. That produced intermittent SS-NAV / SS-LOOP
  // failures which never reproduced in isolation. Waiting for idle fixes
  // the cause instead of retrying the click, so a genuinely broken arrow
  // still fails.
  async waitForIdle(index = 0, timeout = 5_000) {
    await this.section(index)
      .locator(this.s.swiper)
      .first()
      .evaluate(
        (el, ms) =>
          new Promise((resolve) => {
            const deadline = performance.now() + ms;
            const check = () => {
              if (!el.swiper || !el.swiper.animating || performance.now() > deadline) resolve();
              else requestAnimationFrame(check);
            };
            check();
          }),
        timeout
      )
      .catch(() => {
        /* No Swiper instance — the DOM-only checks still apply. */
      });
  }

  // Advance the carousel and wait for the active slide to change.
  async goToNextSlide(index = 0) {
    await this.waitForIdle(index);
    const before = await this.realIndex(index);
    await this.nextArrow(index).click();
    return this.waitForActiveChange(index, before);
  }

  // Step the carousel back and wait for the active slide to change.
  async goToPrevSlide(index = 0) {
    await this.waitForIdle(index);
    const before = await this.realIndex(index);
    await this.prevArrow(index).click();
    return this.waitForActiveChange(index, before);
  }

  // Click pagination bullet `n` and wait for the slide to change.
  async clickBullet(n, index = 0) {
    await this.waitForIdle(index);
    const before = await this.realIndex(index);
    await this.bulletAt(n, index).click();
    return this.waitForActiveChange(index, before);
  }

  // Walk the carousel forward `steps` times, returning the trail of
  // indices reached. Unlike goToNextSlide() this TOLERATES a click that
  // does not move: a dead-end shows up as repeated entries in the trail
  // (which the boundary checks report), rather than as a bare timeout
  // that says nothing about where it stopped.
  async walkNext(steps, index = 0) {
    const trail = [];
    for (let i = 0; i < steps; i++) {
      await this.waitForIdle(index);
      const before = await this.realIndex(index);
      await this.nextArrow(index).click().catch(() => {});
      await this.waitForActiveChange(index, before).catch(() => {});
      trail.push(await this.realIndex(index));
    }
    return trail;
  }

  // Which slide the user is actually looking at, as a 1-based position.
  // Read from Swiper's own "N / total" aria-label on the active slide,
  // which stays correct under loop reordering — so comparing it with
  // realIndex is a genuine desync check.
  async visibleSlidePosition(index = 0) {
    const label = (await this.activeSlide(index).getAttribute('aria-label')) ?? '';
    const match = label.match(/(\d+)\s*\/\s*(\d+)/);
    return match ? Number(match[1]) : -1;
  }

  // ── Swiper introspection ────────────────────────────────────
  // The theme drives the carousel with Swiper, which exposes its live
  // config on the element. Reading it means loop/autoplay tests assert
  // against the ACTUAL configuration instead of a guess — and skip
  // honestly when a preset has the feature switched off.
  async swiperState(index = 0) {
    return this.section(index)
      .locator(this.s.swiper)
      .first()
      .evaluate((el) => {
        const sw = el.swiper;
        if (!sw) return null;
        return {
          loop: !!sw.params?.loop,
          autoplayEnabled: !!sw.params?.autoplay?.enabled,
          autoplayDelay: sw.params?.autoplay?.delay ?? null,
          pauseOnMouseEnter: !!sw.params?.autoplay?.pauseOnMouseEnter,
          speed: sw.params?.speed ?? null,
          realIndex: sw.realIndex,
          activeIndex: sw.activeIndex,
          slides: sw.slides?.length ?? 0,
        };
      });
  }

  // Current index as Swiper reports it (loop-safe, unlike the DOM class).
  async realIndex(index = 0) {
    return (await this.swiperState(index))?.realIndex ?? -1;
  }

  // Horizontal translate of the track, in px. Negative = advanced.
  async trackTranslate(index = 0) {
    return this.section(index)
      .locator('.swiper-wrapper')
      .first()
      .evaluate((el) => new DOMMatrixReadOnly(getComputedStyle(el).transform).m41);
  }

  // Rendered width of a single slide, used to sanity-check how far a
  // navigation actually moved the track.
  async slideWidth(index = 0) {
    const box = await this.slideAt(0, index).boundingBox();
    return box?.width ?? 0;
  }

  // CSS transition property on the track — SS-PERF-02 wants transform
  // or opacity, never a layout property such as `left`.
  async trackTransitionProperty(index = 0) {
    return this.section(index)
      .locator('.swiper-wrapper')
      .first()
      .evaluate((el) => getComputedStyle(el).transitionProperty);
  }

  // Configured slide heights, read from the CSS custom properties the
  // section sets inline (--desktop-height / --mobile-height). Lets the
  // height-setting checks compare rendered geometry against the value
  // the merchant actually configured.
  async heightSettings(index = 0) {
    return this.section(index).evaluate((el) => {
      const style = getComputedStyle(el);
      const px = (name) => parseFloat(style.getPropertyValue(name)) || null;
      return { desktop: px('--desktop-height'), mobile: px('--mobile-height') };
    });
  }

  // The image actually on screen for the active slide.
  //
  // The theme ships TWO <img> per slide — a desktop and a mobile asset —
  // and toggles them with `d-none` rather than <picture>/srcset. Taking
  // .first() therefore returns the desktop image at every viewport, which
  // made the mobile-swap check believe no mobile asset existed. Match the
  // VISIBLE image instead, falling back to the first if the theme ever
  // renders only one.
  async activeImageSource(index = 0) {
    const visible = this.activeSlide(index).locator('img:visible').first();
    const target = (await visible.count()) > 0
      ? visible
      : this.activeSlide(index).locator('img').first();

    return target.evaluate((img) => (img.currentSrc || img.src || '').split('?')[0]);
  }

  // CTAs belonging to the ACTIVE slide only, for geometry comparisons.
  activeCtas(index = 0) { return this.activeSlide(index).locator(this.s.cta); }

  // How far a button's LABEL sits from the button's own centre, plus the
  // padding either side. Measured with a Range around the button's
  // contents — the text node has no box of its own to read.
  async labelCentring(locator) {
    return locator.evaluate((el) => {
      const s = getComputedStyle(el);
      const box = el.getBoundingClientRect();
      const range = document.createRange();
      range.selectNodeContents(el);
      const text = range.getBoundingClientRect();
      return {
        offCentre: (text.x + text.width / 2) - (box.x + box.width / 2),
        padLeft: parseFloat(s.paddingLeft) || 0,
        padRight: parseFloat(s.paddingRight) || 0,
        textAlign: s.textAlign,
      };
    });
  }

  // Whether a text element is cut off inside its own box, and whether
  // the CSS allows a long unbroken word to wrap at all.
  async textBreakMetrics(locator) {
    return locator.evaluate((el) => {
      const s = getComputedStyle(el);
      return {
        clippedX: el.scrollWidth > el.clientWidth + 1,
        clippedY: el.scrollHeight > el.clientHeight + 1,
        scrollW: el.scrollWidth,
        clientW: el.clientWidth,
        canBreakLongWords:
          ['anywhere', 'break-word'].includes(s.overflowWrap) ||
          ['break-all', 'break-word'].includes(s.wordBreak),
        label: (el.textContent ?? '').trim().slice(0, 40),
      };
    });
  }

  // Focusable elements that live inside slides which are NOT active —
  // tabbing into these scrolls the user to something invisible.
  offscreenFocusables(index = 0) {
    return this.section(index).locator(
      `${this.s.slide}:not(.swiper-slide-active) a, ${this.s.slide}:not(.swiper-slide-active) button`
    );
  }

  // Drag across the carousel to emulate a swipe. `dx` negative swipes
  // left (advance), positive swipes right (go back).
  async swipe(dx, index = 0) {
    const box = await this.section(index).boundingBox();
    if (!box) throw new Error('slideshow has no bounding box to swipe on');

    const y = box.y + box.height / 2;
    const startX = box.x + box.width / 2 - dx / 2;

    await this.page.mouse.move(startX, y);
    await this.page.mouse.down();
    // Several intermediate moves — a single jump is often ignored as a
    // click rather than a drag.
    for (let step = 1; step <= 8; step++) {
      await this.page.mouse.move(startX + (dx * step) / 8, y, { steps: 2 });
    }
    await this.page.mouse.up();
    await this.page.waitForTimeout(600);
  }

  // The visual properties a theme realistically uses to signal hover or
  // focus. Captured as one string so "did anything change?" is a single
  // comparison rather than a pile of individual assertions.
  // Includes ::before and ::after: themes frequently animate a pseudo-
  // element rather than the control itself (an underline that grows, a
  // ring that scales). Reading only the element would report "no hover
  // state" on a control that visibly has one.
  async styleSnapshot(locator) {
    return locator.evaluate((el) => {
      const read = (pseudo) => {
        const s = getComputedStyle(el, pseudo);
        return [
          s.backgroundColor, s.color, s.borderColor, s.opacity,
          s.boxShadow, s.transform, s.outlineWidth, s.outlineStyle,
          s.textDecorationLine, s.filter, s.width, s.height,
        ].join(',');
      };
      return [read(null), read('::before'), read('::after')].join(' | ');
    });
  }

  // Hover an element and let its CSS transition finish before reading
  // the result — a theme that animates its hover over 300ms looks
  // unchanged if you measure the instant the pointer arrives.
  async hoverAndSettle(locator, settle = 450) {
    await locator.hover();
    await this.page.waitForTimeout(settle);
  }

  // Move the pointer well away from any control, so the next snapshot
  // is a genuine resting state rather than a lingering hover.
  async resetPointer() {
    await this.page.mouse.move(0, 0);
    await this.page.waitForTimeout(250);
  }

  // Accessible name of a control, however the theme supplies it.
  async accessibleName(locator) {
    return (
      (await locator.getAttribute('aria-label')) ??
      (await locator.getAttribute('title')) ??
      (await locator.innerText().catch(() => '')) ??
      ''
    );
  }
}

export default SlideshowPage;
